### ISSUE TITLE
Update to latest ESLint version

### ISSUE THREAD

**Issue by scrapmac** [adametry/gulp-eslint#111]
Hi, gulp-eslint still uses version 1.0.0. Current released version of ESLint is [1.7.3](http://eslint.org/blog/2015/10/eslint-v1.7.3-released/) . Any plans to update to the latest version?

Not 100% sure, but since there are no breaking changes in the API, upgrade should be seamless.

**Comment by adametry** [comment]
The version is set to ^1.0.0, which effectively means 1.0.0 and greater, but below 2.0.0. Read the common on #111 for info on this works.

The version gets updated when gulp-eslint requires an API available at a specific version. For example, the current release candidate requires eslint@^1.4.0 because it supports the "fix" option introduces with eslint @1.4.0. Dependents can still use the "latest" of eslint until eslint@2.0.0, which will likely have breaking API changes for gulp-eslint to adopt.
