### ISSUE TITLE
Globals not working if ecmaFeatures is set

### ISSUE THREAD

**Issue by josh18** [adametry/gulp-eslint#120]
When `ecmaFeatures` is set in the eslint settings it stops the `globals` option from working. For example when I have
```js
// gulpfile.js
gulp.task('test', function() {
    return gulp.src('test.js')
        .pipe(eslint({
            rules: {
                'no-undef': 2
            },
            globals: {
                foo: true
            },
            ecmaFeatures: {
            },
        }))
        .pipe(eslint.format());
});
```
```js
// test.js
var bar = foo;
```
I get the error message:
```
1:11  error  "foo" is not defined  no-undef
```
However when I remove this line from my gulpfile
```js
ecmaFeatures: {
},
```
I get no error messages.

This seems like a strange problem so it might be that I'm doing something wrong. Let me know if you need any more info. All the node modules should be up to date as I just installed them today.

**Comment by badeball** [comment]
I'm having the same issue. It's very annoying and basically breaks everything. [These](https://github.com/adametry/gulp-eslint/blob/v1.1.0/util.js#L97-L100) lines seems to be the culprit. I'm not quite sure what was the intention there, are they necessary?

**Comment by lukewaite** [comment]
I'm seeing the exact same behaviour when `extends` is set, which the above lines also are conditional upon.

**Comment by adametry** [comment]
This is definitely a bug. As @badeball pointed out, the issue happens during option migration. Earlier in the migration, "globals" and "envs" are converted to the "key:true" or "key" for false since ESLint's config expects this format from the ESLint CLI. The bug is that the migration should happen in the opposite order to so that the original "globals" and "envs" are copied to baseConfig before the conversion (though redundant, it covers alternate scenarios). I'll have an updated shortly...

**Comment by adametry** [comment]
To answer @badeball's question, the migration to "baseConfig" happens because there are roughly two types of configuration for ESLint: the linting config (e.g., rules, globals) and CLI/runner config (e.g., useEslintrc, rulePaths). The "baseConfig" option directly sets the linting config. The config that is defined via the gulp-eslint config or the ESLint CLI is the CLI/runner config, which migrates *some* options to the linting config (and occasionally requires odd formats). Unfortunately, the "ecmaFeatures" and "extends" options are not migrated in this way. So, since gulp-eslint has received issues regarding the options (#73, #113), it attempts to migrate the options (and any others) automatically.

**Comment by adametry** [comment]
A patch version of gulp-eslint has been released with a fix for this bug. Grab version 1.1.1 and let me know if you experience any further issues.

**Comment by josh18** [comment]
Seems to be working for me, thanks for the quick response!

**Comment by badeball** [comment]
Can confirm, it works. Thanks for the quick response and release!
