### ISSUE TITLE
How to output formatter to file using gulp

### ISSUE THREAD

**Issue by kburson** [adametry/gulp-eslint#125]
I have the linter working, and the 'checkstyle' formatter works, but it spits output to the console.  I need to pass this to a file.

The standard way of doing that in gulp is to pipe to gulp.dest:

```
gulp.src('src/**/*.js')
.pipe(eslint('.eslintrc'))
.pipe(eslint.format()) // stdout
.pipe(eslint.format('checkstyle'))
.pipe(gulp.dest('reports/checkstyle.xml');
```

But this does not work.  I tried to insert gulp.dest into the `eslint.format('checkstyle',gulp.dest(...))`, 
but that does not work as it is not a writeable stream.

What is the correct way to output the checkstyle formatted report to a file that can be consumed by jenkins?

Thanks,

**Comment by adametry** [comment]
You nearly got it right by trying to use format's second argument. The issue is that [`gulp.dest`](https://github.com/gulpjs/vinyl-fs#destfolder-opt), which writes [vinyl](https://github.com/gulpjs/vinyl) files relative to a base path, isn't quite the right type of writable stream for the job. Instead try [`fs.createWriteStream`](https://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options), which will write a text stream to a file path. 

```javascript
gulp.src('src/**/*.js')
.pipe(eslint('.eslintrc'))
.pipe(eslint.format()) // stdout
.pipe(eslint.format('checkstyle', fs.createWriteStream('reports/checkstyle.xml')));
```

**Comment by kburson** [comment]
Thank you so much, that was the answer!
