### ISSUE TITLE
No output from #format if the last item

### ISSUE THREAD

**Issue by rosskevin** [adametry/gulp-eslint#134]
```javascript
gulp.task('lint', function () {
    return gulp.src(['**/*.js','!node_modules/**'])
        .pipe(eslint())        
        .pipe(eslint.format()); // outputs the lint results to the console.
});
```

Perhaps this is user error, but it appears that if `.pipe(eslint.format())` is the last piped item, there is no output.  Is this a bug or am I missing a gulp fundamental here?

**Comment by adametry** [comment]
There may be an environmental variable at play here. `format` waits until the end of its stream (specifically, the "prefinish" event) to process and write (to console by default). Often this issue happens when a gulp task doesn't return the last stream; which results in gulp not waiting for it to complete. However, in this case I the example code appears to work fine.

Could you run `gulp lint && echo process done` to show me what your console produces?

**Comment by rosskevin** [comment]
```bash
$ gulp eslint && echo 'process done'
[10:00:11] Requiring external module babel-core/register
[10:00:13] Using gulpfile ~/projects/acme/gulpfile.babel.js
[10:00:13] Starting 'eslint'...
[10:00:13] Finished 'eslint' after 19 ms
process done
```

**Comment by adametry** [comment]
Is that the output from running the example you provided above?

**Comment by adametry** [comment]
Based on the #135 issue and that your console output appears to use your `gulp-pipeline` library, I took a look at how you're constructing gulp tasks. It turns out that the problem actually *is* that the stream isn't returned in the gulp task (in [taskSeries](https://github.com/alienfast/gulp-pipeline/blob/5021a71990231530ede87c4e10e4d13abb754bfd/src/taskSeries.js#L27) and [baseRecipe](https://github.com/alienfast/gulp-pipeline/blob/e49bf6830c6cfbe22b8a018236061d0f38037a54/src/baseRecipe.js#L68)). This means the gulp task will not wait for the async stream to finish and will consider it complete on the next tick. Since your individual tasks do return from their `run` method, just make sure that returned stream is returned by  the gulp task definition, like it is in the example your provided above.

**Comment by rosskevin** [comment]
Confirmed.  **Thank you so much** for taking time to look at this code.  `#format` indeed works as advertised.
