### ISSUE TITLE
eslint@2.3.0 and babel-eslint

### ISSUE THREAD

**Issue by tupton** [adametry/gulp-eslint#145]
See eslint/eslint#5476, babel/babel-eslint#267, eslint/eslint#5494, possibly others.

The gist is that `eslint@2.3.0` breaks with `babel-eslint` and possibly other alternative parsers.

`gulp-eslint` specifies `^2.0.0` which means that new installations grab 2.3.0 now. Is there any way you can pin to 2.2.x – `~2.2.0` – until eslint@2.3.0+ stabilizes?

**Comment by adametry** [comment]
I'm going to hold off on publishing a version of gulp-eslint to downgrade ESLint since this is an ESLint issue specific to the use of babel-eslint (rather than an incompatibility between gulp-eslint and ESLint). 

Fortunately, you can "pin" the version of ESLint that gulp-eslint uses by depending on a more specific version in your package (or any package dependent on gulp-eslint). The only restriction is that is has to be within the gulp-eslint dependency range (currently, any 2.x version).

**Comment by tupton** [comment]
I totally understand not pinning to 2.2.x just for babel-eslint. I hesitated even making this issue because of that. However, I am glad I did because of your second paragraph...

> Fortunately, you can "pin" the version of ESLint that gulp-eslint uses by depending on a more specific version in your package (or any package dependent on gulp-eslint).

Oh that is nifty. You learn something every day. Thanks for that tip; that's a lifesaver. That restriction makes sense, but fortunately 2.2.x is in that range, so I think we're good. Again, thanks for the response and tip.
