### ISSUE TITLE
Bump eslint to 2.2.0

### ISSUE THREAD

**Issue by KrisOlszewski** [adametry/gulp-eslint#146]
Hi there! Thanks for a great plugin. Do you mind bumping `eslint` to 2.2.0? There is a bug that completely breaks the build. 

See here: https://github.com/eslint/eslint/issues/5476

**Comment by adametry** [comment]
See here: #145.

Until the issue is fixed in ESLint, you can control the version of ESLint used by gulp-eslint by declaring a more specific ESLint version dependency in your package.json. The only restriction is that it's within gulp-eslint's own ESLint dependency range (currently, any 2.x version).

**Comment by KrisOlszewski** [comment]
Ahh, ok. Thanks for the info!
