### ISSUE TITLE
Using src from the parent folder of gulpfile.js will not be linted

### ISSUE THREAD

**Issue by trajano** [adametry/gulp-eslint#148]
For a Meteor project we have to keep the `gulpfile.js` and `node_modules` in a folder that is not visible to meteor otherwise it will compile them.  This means putting `gulpfile.js` into a dot subfolder like `.gulp` which is what https://github.com/bbmoz/meteor-gulp/ does.  The gulpfile it generates looks something like this.

https://github.com/bbmoz/meteor-gulp/blob/master/plugin/gulpfile.temp

Their example uses jshint and jscs but I'd rather use eslint because it's a bit easier to configure for Angular and ES6.  However when the `./../** ...` globs get passed to eslint it does not get processed.  I have verified that the files will match the glob if I use `gulp-print` to print out the file list.  My current workaround is to reorganize the project such that gulpfile is in the parent folder and my meteor is in a sub folder.

**Comment by saviomd** [comment]
+1

My folder structure is:
```
/gulp/gulpfile.js
/WebContent/javascript/**/*.js
```
This worked in previous versions but it doesn't anymore, I *think* 2.0.0 broke it..

**Comment by adametry** [comment]
Try adding `warnFileIgnored:true` to your gulp-eslint config. If you receive a bunch of ignore warnings let me know and I'll dig into why the linter might give mixed messages (gulp-eslint uses eslint's [`isPathIgnored`](https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L660) to avoid linting .eslintignore'd files).

**Comment by catherinelamonde** [comment]
I have the same bug.
«return gulp.src([ "../test/**/*.js"...» do not lint.
«return gulp.src([ "test/**/*.js"...» do lint.
When I add «warnFileIgnored: true»it gives me : 
«/Users/clamonde/Sites/axxium/test/simple-accordion.js
  0:0  warning  File ignored because of .eslintignore file.»

**Comment by adametry** [comment]
Thanks, @catherinelamonde. I've found that ESLint has some problems with relative ".eslintignore" paths when dropping a directory. Can you tell me where your ".eslintignore" file is and list its paths. I'm working toward the root of this issue. In the meantime, you may be able to use the `ignore:false` option to disable this validation by `gulp-eslint` and `ESLint`.

On a side note, it would be more efficient to ignore files from `gulp.src` since gulp will read/load a file's content even if it's ignored by ESLint. This is especially true for _node_modules/**_ paths. However, I've seen examples that just load _***/**.js_ and expect ESLint to skip files based on ".eslintignore" and the ESLint internal ignores (i.e., _node_modules/**_). In some cases, having `gulp.src` ignore files can shave seconds off a task's time.

**Comment by shinnn** [comment]
```
├ project (cwd)
│ ├ gulpfile.js
│ └ package.json 
│
└ script.js 
```

`package.json`:

```json
{
  "name": "test",
  "private": true,
  "devDependencies": {
    "gulp": "gulpjs/gulp#d8f5c90a0622d19ef1943a2a3d02dc50e3c853e7",
    "gulp-eslint": "^3.0.1"
  }
}
```

`gulpfile.js`:

```js
'use strict';
const gulp = require('gulp');
const eslint = require('gulp-eslint');

gulp.task('default', () => {
  return gulp.src('../script.js')
  .pipe(eslint({
    useEslintrc: false,
    rules: {
      camelcase: 'error'
    }
  }))
  .pipe(eslint.format());
});
```

`script.js`:

```js
a_b = c
```

```
$ node -v
v6.3.0

$ npm -v
3.10.5

$ node node_modules/gulp/bin/gulp.js
[03:22:50] Using gulpfile ~/test/project/gulpfile.js
[03:22:50] Starting 'default'...
[03:22:50] 
/Users/Shinnosuke/test/script.js
  1:1  error  Identifier 'a_b' is not in camel case  camelcase

✖ 1 problem (1 error, 0 warnings)

[03:22:50] Finished 'default' after 75 ms
```

======

This issue seems to be fixed in the latest version.
