### ISSUE TITLE
Not recursive

### ISSUE THREAD

**Issue by ericntd** [adametry/gulp-eslint#150]
my project folder structure is like the following:
```
/project-root/
    gulpfile.js
    myjsstuffs/
        somescript.jsx
        module1/
            script1.jsx
            dir1/
                 script2.jsx
                 subdir1/
                      script3.jsx
```
Only `somescript.jsx` and `script1.jsx` are being linted at the moment.
My gulp task:
```
gulp.task('lint', function() {
    console.log('lintAf');
    gulp.src(['!node_modules/**', '!bower_components/**', '!build/**', '!public/**', '!styles/**', '!views/**', 'myjsstuffs/**/*'])
    .pipe(eslint())
    .pipe(eslint.formatEach('stylish'));
});
```
I'm using `gulp-eslint` version 2.0.0

**Comment by rosskevin** [comment]
@ericntd add [gulp-debug](jhttps://github.com/sindresorhus/gulp-debug) after `gulp.src` to see which files you are passing to `eslint()`.  `gulp.src` uses node-glob, and I don't think it supports negation any longer, you need to use the second options parameter with `{ignore: []}`.  I don't think this is a problem with this plugin.

**Comment by rosskevin** [comment]
Ah, to debug, also add the `warnFileIgnored: true` to the options just in case.

**Comment by adametry** [comment]
@rosskevin, good debugging tips. Negated paths still work since gulp still uses [node-glob@5.0.3](https://github.com/gulpjs/glob-stream/blob/master/package.json#L25). All the same, the negated paths are mostly useless since only files within "myjsstuffs" are pulled in.

Also, be sure to return the stream from your task. It's likely that the process is exiting before it can load, lint, and print every tile.

Try this:
```javascript
gulp.task('lint', function() {
    console.log('lintAf');
    return gulp.src(['myjsstuffs/**/*'])
        .pipe(eslint())
        .pipe(eslint.formatEach('stylish'));
});
```

**Comment by ericntd** [comment]
@adametry thanks, worked like a charm
