### ISSUE TITLE
require('eslint/lib/util') fails in util.js

### ISSUE THREAD

**Issue by NickPowers43** [adametry/gulp-eslint#172]
I am trying to use gulp in [this](https://github.com/ooflorent/js13k-boilerplate) project. gulp-eslint fails to load the necessary modules for it to work though.

**Comment by NickPowers43** [comment]
According to the Node.js [docs](https://nodejs.org/api/modules.html) there should be either a package.json, index.js, or index.node file inside eslint/lib/util/.

**Comment by NickPowers43** [comment]
I dont see one though

**Comment by adametry** [comment]
The package.json in js13k-boilerplate has a dependency on an an 1.x version of eslint, but it's installing a more recent version of eslint (3.x). Because the structure of eslint has changed since gulp-eslint 1.8 was current, this error occurs when requiring the old location of ab eslint module.

Update the gulp-eslint version to 2.x or latest (3.x) to get things working.

**Comment by NickPowers43** [comment]
Thanks for the response. I came to the same conclusion last night. Sorry for not updating the issue.
