### ISSUE TITLE
transpile module to es5

### ISSUE THREAD

**Issue by darlanmendonca** [adametry/gulp-eslint#182]
Hi @adametry, I use your module ever, thanks :D

But in a specific project, we run tasks on CI, and when we run on node 0.10 for example, the module broken. A friend tell me that you dropped the support to node 0.10, is truth?

If yes, what your motivations? I like know it, just for knowledge sure :D

Now if you wish, I can do a PR to transpile es6 to es5 (maintain the code in es6, but create a file to be exported in main file in es5)

**Comment by shinnn** [comment]
> we run on node 0.10

[Node 0.10 is dead](https://github.com/nodejs/LTS/tree/9615f48c18396cac61d777a7e02b73b29b265393#lts-schedule). 

> the module broken.

Not broken. That is just an expected behavior of the latest gulp-eslint.

> A friend tell me that you dropped the support to node 0.10, is truth?

Please check CHANGELOG, git commit log and closed issues before asking questions.

> what your motivations?

Because [the upstream project](https://github.com/eslint/eslint) successfully dropped Node < v4.0.0 support. http://eslint.org/blog/2016/07/eslint-v3.0.0-released

> I can do a PR to transpile es6 to es5

Sorry, no thanks. I really agree to the decision of ESLint team to drop ancient Node support. Pin `gulp-eslint` version of your project's package.json to `"2.1.0"` instead.

**Comment by darlanmendonca** [comment]
yeah, I understand, and I agree with that decision, is a good point.

Thanks for all
