### ISSUE TITLE
Support for eslint 0.24.0

### ISSUE THREAD

**Issue by doberkofler** [adametry/gulp-eslint#70]

**Comment by cmaher** [comment]
Since eslint is updated rather frequently, it might be a good idea to allow the user to provide their own version of eslint when calling this plugin.  At the very least, it would enable users to update eslint without waiting for this plugin to update as well

I imagine this would involve replacing https://github.com/adametry/gulp-eslint/blob/master/index.js#L15 with something like

```js
var Engine = options.CLIEngine || CLIEngine;
var linter = new Engine(options);
```

or any number of alternatives.  It also looks like `util.resolveFormatter` would also need to change.
I'd be happy to work on this if you think it's a good idea, @adametry.

**Comment by doberkofler** [comment]
@cmaher I think this is a great idea.

**Comment by inikulin** [comment]
+1

**Comment by oluckyman** [comment]
btw, eslint 0.24.0 is the last release before 1.0.0.

**Comment by adametry** [comment]
A config-defined eslint creates more problems than it solves. Besides side-stepping the tested eslint version, it makes changes to how gulp-eslint uses eslint a potential breaking API change. It's also worth noting that substantial changes to internal eslint modules change (e.g., CLIEngine) are not uncommon, and I expect 1.0.0 will have several breaking changes.

On the bright side, gulp-eslint@0.15.0 – using eslint@0.24.0 – is now available.

**Comment by oluckyman** [comment]
Thanks!
