### ISSUE TITLE
.eslintignore not working consistently with eslint cli

### ISSUE THREAD

**Issue by adammockor** [adametry/gulp-eslint#85]
My .eslintignore looks like this:
```
**/*.js
!app/scripts/*.js
!app/scripts/modules/**/*.js
```
If I run `eslint .` it only lints files within scripts root and in modules folder as it should.

When I start gulp task like this, all my files are ignored.
```
gulp.task('lintjs', 'Lint js files', function () {
  return gulp.src('app/scripts/**/*.js')
    .pipe(eslint())
    .pipe(eslint.format())
    .on('error', handleError);
});
```
With undocumented option eslint({ignore: false}) it works as expected.

**Comment by onlywei** [comment]
I am also having this issue, although `{ignore: false}` is not working for me because that will ignore nothing.

My `.eslintignore` file looks like this:
```
client/jspm_packages/**
client/config.js
```
The documentation for eslint says that `node_modules/**` is ignored by default, but I have tried including it explicitly and still not getting desired results.

Gulp task looks like this:
```
gulp.task('lint', () => {
  return gulp.src('**/*.js')
    .pipe(eslint())
    .pipe(eslint.format())
    .pipe(eslint.failOnError());
});
```

Just like @adammockor says, using `eslint .` from the command line works, BUT running `gulp lint` with the above settings results in:

```
16:29:29] ESLintError in plugin 'gulp-eslint'
Message:
    Extra semicolon.
Details:
    fileName: /path/to/code/node_modules/jspm/node_modules/request/node_modules/qs/lib/index.js
    lineNumber: 3
```

How come it linted that file inside my `node_modules`?

**Comment by adametry** [comment]
@adammockor, this is certainly a bug. I'll have a fix for this ready within the next day or two.

@onlywei, while this exhibits the same bug (which will be fixed), I recommend ignoring node_modules from gulp.src rather than relying on eslint to ignore the files. This plugin uses gulp to locate and read files, and uses eslint to lint the content from the gulp/vinyl stream. This means that gulp still reads every qualifying file in node_modules whether or not eslint ignores the path. In packages with a complex dependency tree, this can result in poor task performance.

The upcoming update will better align gulp-eslint with eslint's ignore patterns. I'll be sure to add an update here once it's ready.

**Comment by adametry** [comment]
Well, it was a looooong "day or two", but I've pushed a release candidate that better adheres to Eslint's file ignoring ways. Check it out when you get the chance and let me know how it works out.
```javascript
npm install gulp-eslint@rc
```

**Comment by gwilakers** [comment]
@adametry Ran this through my code a few times (~200 file backbone project using babel), looks pretty good to me. Also just an FYI, I am using a .eslintignore file and it seems to ignore those files.

**Comment by adametry** [comment]
@gwilakers, is it ignore the .eslintignore file itself (an issue) or the files it references (normal behavior)? If It's ignoring the .eslintignore, please create an issue with some details and I'll look into it.

**Comment by adametry** [comment]
gulp-eslint@1.1.0 has been released. I'll close this bug since a fix for it has been released. If there are any further problems, let me know.
